$inherits:
  from: 'tasks/builds/b2g_public_phone_base.yml'
task:
  workerType: balrog

  payload:
    env:
      DEBUG: 0
      MOZHARNESS_CONFIG: b2g/taskcluster-nexus-fota.py
      B2G_UPDATE_CHANNEL: '{{b2g_update_channel}}'
    command:
      - >
        checkout-gecko workspace &&
        cd ./workspace/gecko/testing/taskcluster/scripts/phone-builder &&
        buildbot_step 'Build' ./build-phone-ota.sh $HOME/workspace

  extra:
    treeherder:
      machine:
        platform: b2g-device-image
    locations:
      mar: 'public/build/b2g-aries-gecko-update.mar'
