$inherits:
  from: 'tasks/builds/b2g_aries_ota_opt.yml'
task:
  scopes:
    - 'docker-worker:feature:balrogVPNProxy'
  payload:
    features:
      balrogVPNProxy: true
    env:
      MOZHARNESS_CONFIG: b2g/taskcluster-ota-balrog.py
