$inherits:
  from: 'tasks/builds/b2g_nexus_fota_base.yml'
  variables:
    build_name: 'nexus-fota'
    build_type: 'debug'
task:
  metadata:
    name: '[TC] B2G Nexus 5 L FOTA'
  scopes:
    - 'docker-worker:cache:build-nexus-5-l-userdebug'
    - 'docker-worker:cache:build-nexus-5-l-userdebug-objdir-gecko-{{project}}'
  payload:
    cache:
      build-nexus-5-l-userdebug: /home/worker/workspace
      build-nexus-5-l-userdebug-objdir-gecko-{{project}}: /home/worker/objdir-gecko
    env:
      TARGET: 'nexus-5-l'
      VARIANT: userdebug
      MOZHARNESS_CONFIG: b2g/taskcluster-nexus-fota.py
      B2G_UPDATE_CHANNEL: '{{b2g_update_channel}}'
  extra:
    locations:
      img: 'public/build/hammerhead.zip'
    treeherderEnv:
      - production
      - staging
    treeherder:
      symbol: B
      groupSymbol: Nexus 5 L Userdebug
      groupName: Nexus5l Device Image
      machine:
        platform: b2g-device-image
      collection:
        debug: true
