$inherits:
  from: 'tasks/builds/b2g_aries_ota_base.yml'
  variables:
    build_name: 'aries-ota'
    build_type: 'debug'
task:
  metadata:
    name: '[TC] B2G Aries OTA (userdebug)'
  scopes:
    - 'docker-worker:cache:build-aries-ota-debug'
    - 'docker-worker:cache:build-aries-ota-debug-objdir-gecko-{{project}}'
  payload:
    cache:
      build-aries-ota-debug: /home/worker/workspace
      build-aries-ota-debug-objdir-gecko-{{project}}: /home/worker/objdir-gecko
    env:
      VARIANT: userdebug
      B2G_DEBUG: 0
  extra:
    treeherderEnv:
      - staging
    treeherder:
      symbol: B
      groupSymbol: Aries-OTA
      groupName:  Aries Device Image
      machine:
        platform: b2g-device-image
      collection:
        debug: true
